{% set name = "scikit-build" %}
{% set version = "0.10.0" %}
{% set sha256 = "e18abd90c4cf445e8219282d18ed4bbff0aa928706a68cccc3ac037562a97bf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Replace-platform.linux_distribution-with-distro.id.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - cmake
    - ninja
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - packaging
    - pip
    - python
    - setuptools
    - wheel
  run:
    - cmake
    - distro
    - packaging
    - python
    - ninja
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  requires:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - mock
    - path.py
    - pytest
    - pytest-mock
    - pytest-cov
    - pytest-runner
    - six
    - git
    - cmake
    - ninja
    - cython
    - requests

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Improved build system generator for CPython C extensions.'
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
