{% set name = "scikit-build" %}
{% set version = "0.8.1" %}
{% set sha256 = "dbee97088fc878a05b70482c182141359a81615dc1d969ddbf09e919f94efca9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - cmake
    - ninja
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - packaging
    - pip
    - python
    - setuptools
    - wheel
  run:
    - cmake
    - packaging
    - python
    - ninja
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  commands:
    - py.test -k "not test_fortran_compiler and not test_issue352_isolated_environment_support"  # [unix]
    - py.test -k "not test_fortran_compiler and not test_issue352_isolated_environment_support and not test_cmake_install_dir_keyword"  # [win]
  requires:
    - mock
    - path.py
    - pytest
    - pytest-mock
    - pytest-cov
    - pytest-runner
    - six
    - git
    - cmake
    - ninja
    - cython
    - requests

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Improved build system generator for CPython C extensions.'
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
