{% set version = "0.18.0" %}
{% set sha256 = "71a13af467d1a38510c3494786e2edb73ead53ea922bde6e519dc5372aa65096" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-build/scikit_build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python


requirements:
  host:
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.7
  run:
    - distro
    - packaging
    - python >=3.7
    - setuptools
    - tomli
    - typing-extensions
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
    - pyproject.toml
  commands:
    - pip check
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
    - git
    - make
    - path.py
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
    - setuptools
    - virtualenv
    - wheel

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
    - henryiii
    - mayeut
