{% set version = "0.18.1" %}
{% set sha256 = "a4152ac5a084d499c28a7797be0628d8366c336e2fb0e1a063eb32e55efcb8e7" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/scikit-build/scikit_build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python


requirements:
  host:
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - distro
    - packaging
    - python >={{ python_min }}
    - setuptools
    - tomli
    - typing-extensions
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
    - pyproject.toml
  commands:
    - pip check
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
    - git
    - make
    - path.py
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
    - setuptools
    - virtualenv
    - wheel
    - python {{ python_min }}

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
    - henryiii
    - mayeut
