{% set version = "0.12.0" %}
{% set sha256 = "c32a415d2e7920a4a966b037403c93b02c8a958d8badf3c60abd4b4493f7d988" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python


requirements:
  host:
    - packaging
    - pip
    - python >=2.7
    - setuptools
    - wheel
  run:
    - cmake
    - distro
    - ninja
    - packaging
    - python >=2.7
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
    - git
    - make  # [unix]
    - mock
    - ninja
    - path.py
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-runner
    - requests
    - setuptools <60
    - six

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
    - henryiii
    - mayeut
