{% set version = "0.10.0" %}
{% set sha256 = "2beec252813b20327072c15e9d997f15972aedcc6a130d0154979ff0fdb1b010" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Replace-platform.linux_distribution-with-distro.id.patch
    - 0002-FindPythonExtensions-Fix-deprecated-warning-and-use-correct-python-extension-suffix-on-windows.patch
    - 0003-Use-the-MACOSX_DEPLOYMENT_TARGET-env-variable.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - cmake
    - ninja
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - packaging
    - pip
    - python
    - setuptools
    - wheel
  run:
    - cmake
    - distro
    - packaging
    - python
    - ninja
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  requires:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - mock
    - path.py
    - pytest
    - pytest-mock
    - pytest-cov
    - pytest-runner
    - six
    - git
    - cmake
    - ninja
    - cython
    - requests

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Improved build system generator for CPython C extensions.'
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
