{% set name = "scikit-build" %}
{% set version = "0.6.1" %}
{% set sha256 = "998a731eb4d1160e848717bbbec046d9b37f748b4f3e902562bc7d22e82b2721" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - wheel
  run:
    - python
    - setuptools
    - wheel
    - cmake
    - ninja

test:
  imports:
    - skbuild
  commands:
    - cd ${SRC_DIR} && py.test -k "not test_fortran_compiler"    # [unix]
    - cd %SRC_DIR% && py.test -k "not test_fortran_compiler"     # [win]
  requires:
    - path.py
    - pytest
    - pytest-mock
    - pytest-cov
    - six
    - git
    - cmake
    - ninja
    - cython

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Improved build system generator for CPython C extensions.'
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
