{% set version = "0.16.2" %}
{% set sha256 = "caf5b4da9bd7e88232b40050cde584f1e252fed44f12034c36a9ca86444a6c42" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-build/scikit-build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python


requirements:
  host:
    - packaging
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - cmake
    - distro
    - make
    - packaging
    - python >=3.6
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  commands:
    - pip check
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython
    - git
    - path.py
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
    - setuptools
    - wheel <0.38

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
    - henryiii
    - mayeut
