travis:
  secure:
    BINSTAR_TOKEN: M0yoipT42I94PhHTdoOKrj5pQAuohcLl0B6ujnsOrvmjhVmFg8VzE8iT2xm5ie9QEBYwlp5pZAvICcTK1Moxv3/kQaNJsoMjLIhF18xsiNg5c+kddaAa5RY/ZtT/3SCNF0G/EZg7w9eIBhyNBOZ3rdPIdv8UtFJGeEx/e38geM0/HeEfLskUSUH4hvHkwZclE4n1cN7xwqPf7YT1KRYYoynVCs5JtA2ztmMFosz/Y0W11SodMZPcQf6jx5gwXafa+Ejlo9IZB0NLEiLRIaoUyeRTnPsAx9DIo2pcyZzcFvVI8xVF9aiKamUOVx/xrWwwtAu/M1CWT9A/5iMXCCcOM3wdVX4f6SjF7tX+L8dB49FqfUVS/1ouCaaorjMgc7BhqOrWNfPRW79IHH6Y73GAH0kNJKAOh0KFxNn0qN4ebhWo7ZwJdEdNksox3Bc2K4WTieTYgDyH02WmhPKsMFFqXIXW34/O1aUFL2fzGZANFMIc7FfvUkcGhKa2jkQ9tbfgTiGnv94Wc4GOVtB//jwEu/BZqOvEvNKWR5Wf1xXOIz29TJQ/0/RBpAm6OgD7PRFH/6m4PWxbuU+3grT6iCDnrnkuJTyyWDVHPiQTo7y78NcLH4cyH+DzUIyf/cVFxguyfrQFh1mKNKU1ZWkY9l1A8tFsfyOVcC4cb197XGK4aZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
